### ISSUE TITLE
Unable to run npm install on a fresh checkout

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-node#104]
On a fresh checkout, `npm install` fails:

```
$ git clone git@github.com:pact-foundation/pact-node.git
$ cd pact-node
$ npm install
....

> @pact-foundation/pact-node@6.19.8 postinstall /Users/work/office/pact/test/pact-node
> node postinstall.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './standalone/install'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/work/office/pact/test/pact-node/postinstall.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pact-foundation/pact-node@6.19.8 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @pact-foundation/pact-node@6.19.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/work/.npm/_logs/2018-08-10T04_15_32_144Z-debug.log
```

doing `npm run build` (which also fails, because the dependencies are missing), will generate the module, but then `npm install` fails differently:

```
$ npm install
.... 

Finished downloading binary to /Users/work/office/pact/test/pact-node/standalone/pact-1.54.1-osx.tar.gz
/Users/work/office/pact/test/pact-node/standalone/install.js:263
    throw new Error(chalk.red("Unhandled Promise Rejection: " + e));
    ^

Error: Unhandled Promise Rejection: Postinstalled Failed Unexpectedly: Checksum file missing from standalone directory. Aborting.
    at process.<anonymous> (/Users/work/office/pact/test/pact-node/standalone/install.js:263:11)
    at process.emit (events.js:182:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:105:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pact-foundation/pact-node@6.19.8 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @pact-foundation/pact-node@6.19.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/work/.npm/_logs/2018-08-10T04_18_01_407Z-debug.log
```

Do I have something in my environment configured incorrectly?

Here are my npm and node versions:

```
$ npm --version
6.2.0
$ node --version
v10.8.0
```

**Comment by TimothyJones** [comment]
Seems to work with `npm install --ignore-scripts` - is that the right way to set up a dev environment?

**Comment by mefellows** [comment]
ah, yes this confused me as well. 

I think you first need to run `npm run build` to compile before you can `npm i`. I'm not sure why the watch was removed, albeit I never used it myself personally.

I think this was an issue when we moved to TypeScript (due to the need to compile). Perhaps the install step could be made more clever?

My expectation as a contributor should be to do the following:

```
npm it
```

**Comment by TimothyJones** [comment]
I found that 

```
npm install # This errors, but installs enough that the build will run
npm run build # This errors, but creates the code that install needs
npm install # This now succeeds
```

was what was necessary. Might be able to fix this by changing the post-install script - I'll have a look.

**Comment by TimothyJones** [comment]
Ok, that works, but then errors because the checksums are missing. PR incoming.
