### ISSUE TITLE
pact-mock-service is not found when run in docker container `node:v10.15.3`

### ISSUE THREAD

**Issue by vbotay** [pact-foundation/pact-node#182]
## Software versions

-   **OS**: docker node:10.15.3
-   **Library version**: 9.0.4
-   **node**: v10.15.3

## Expected behaviour

Pact provider initialised and tests are started .

## Actual behaviour

```
[2019-09-16T10:13:01.237Z] ERROR: pact-node@9.0.4/25 on 452dacd35513: 
    Pact Binary Error: /bin/sh: 1: ./standalone/linux-x64-1.70.2/bin/pact-mock-service: not found
```

## Steps to reproduce

Run consumer side contract tests in docker container using image node:10.15.3
**NB**: Everything works fine on version 9.0.3.

**Comment by mefellows** [comment]
Can you please provide a repro for this? 

I've seen this issue before when the node modules from a different host (e.g. Mac OSX) are volume mounted into the container. It should work just fine with Node 10

**Comment by vbotay** [comment]
@mefellows 

here is an example of test
```javascript
const { Pact, Matchers } = require('@pact-foundation/pact');
const path = require('path');
const axios = require('axios');

const SERVICE_NAME = 'service-provider';

describe('When service is our Provider', () => {
    let provider;

    beforeAll(async () => {
        const options = {
            provider: SERVICE_NAME,
            consumer: 'service-consumer',
            log: path.resolve(__dirname, './logs', `pact-${SERVICE_NAME}.log`),
            dir: path.resolve(__dirname, './contracts'),
            logLevel: process.env.LOG_LEVEL || 'WARN',
            spec: 2,
            port: 9090,
        };
        provider = new Pact(options);

        await provider.setup();
    });

    afterEach(async () => {
        await provider.verify();
    });

    afterAll(async () => {
        await provider.finalize();
    });

    test('returns 200 from our service with the right response body', async () => {
        await provider.addInteraction({
            uponReceiving: 'a POST request to /v1/user',
            withRequest: {
                method: 'POST',
                path: '/v1/user',
                headers: {
                    // "Content-Type": "application/json;charset=utf-8",
                },
                body: {
                    name: Matchers.string('Alice'),
                    age: Matchers.string('13'),
                },
            },
            willRespondWith: {
                status: 200,
                headers: { 'Content-Type': 'application/json; charset=utf-8' },
                body: {
                    name: Matchers.string('Alice'),
                    id: Matchers.string('12312313'),
                },
            },
        });
        const { data: body } = await axios.post('http://localhost:9090/v1/user', {
            name: 'Alice',
            age: '13',
        });
        expect(body.name).toBe('Alice');
    });
});
```

1. Install pact node of version 9.0.4 =>  `npm install @pact-foundation/pact-node@9.0.4`
2. start container mounting local dir 
```
docker run  -it -v "$(pwd)"/:/tmp node:10.15.3 /bin/bash
```
3. Inside container: 
```
root@d5090416df14:/# cd /tmp/
root@d5090416df14:/tmp# npm run pact:contract

> service-dcb-web-api@0.6.0 pact:contract /tmp
> CONFIG_ENV=pact NODE_ENV=pactTest jest --testMatch '**/test/pact/**/service.test.pact.js' --runInBand

[2019-09-16T13:58:12.573Z]  INFO: pact-node@9.0.4/19 on d5090416df14:
    Creating Pact Server with options:
    {"consumer":"service-consumer","cors":false,"dir":"/tmp/test/pact/contracts","host":"127.0.0.1","log":"/tmp/test/pact/logs/pact-service-provider.log","pactFileWriteMode":"overwrite","port":9090,"provider":"service-provider","spec":2,"ssl":false}
[2019-09-16T13:58:12.594Z] DEBUG: pact-node@9.0.4/19 on d5090416df14: Starting pact binary with '/bin/sh,-c,./standalone/linux-x64-1.70.2/bin/pact-mock-service service --consumer 'service-consumer' --pact_dir '/tmp/test/pact/contracts' --host '127.0.0.1' --log '/tmp/test/pact/logs/pact-service-provider.log' --pact-file-write-mode 'overwrite' --port '9090' --provider 'service-provider' --pact_specification_version '2',{"cwd":"/tmp/node_modules/@pact-foundation/pact-node","detached":true,"env":{"npm_config_cache_lock_stale":"60000","npm_config_ham_it_up":"","npm_package_scripts_swagger_mock_validator":"./node_modules/swagger-mock-validator/bin/swagger-mock-validator","npm_package_dependencies_read_pkg_up":"^4.0.0","npm_config_legacy_bundling":"","npm_config_sign_git_tag":"","npm_package_devDependencies_eslint_plugin_security":"^1.4.0","npm_package_devDependencies_jest":"^24.9.0","npm_config_user_agent":"npm/6.4.1 node/v10.15.3 linux x64","npm_config_always_auth":"","NODE_VERSION":"10.15.3","npm_package_devDependencies__stryker_mutator_jest_runner":"^2.0.2","npm_package_devDependencies_crypto":"^1.0.1","npm_package_bugs_url":"https://github.com/getndazn/service-dcb-web-api/issues","npm_config_bin_links":"true","npm_config_key":"","YARN_VERSION":"1.13.0","HOSTNAME":"d5090416df14","npm_config_allow_same_version":"","npm_config_description":"true","npm_config_fetch_retries":"2","npm_config_heading":"npm","npm_config_if_present":"","npm_config_init_version":"1.0.0","npm_config_user":"","npm_node_execpath":"/usr/local/bin/node","SHLVL":"1","npm_package_scripts_test_all":"npm test -- --runInBand --testMatch '**/test/(unit|component)/**/**spec.js'","npm_package_dependencies_enjoi":"^6.0.0","npm_config_prefer_online":"","npm_config_noproxy":"","CONFIG_ENV":"pact","HOME":"/root","OLDPWD":"/","npm_config_force":"","npm_config_only":"","npm_config_read_only":"","npm_package_engines_node":"^10.15.0","npm_package_scripts_test_component":"npm test -- --testMatch '**/test/component/**/**spec.js'","npm_package_scripts_test_contract":"node ./test/scripts/runContractsValidator.js -o 6","npm_package_dependencies_axios_mock_adapter":"^1.16.0","npm_package_dependencies_bunyan":"^1.8.12","npm_package_devDependencies_chai":"^4.2.0","npm_config_cache_min":"10","npm_config_init_license":"ISC","npm_package_scripts_start_debug":"node --inspect=0.0.0.0:5858 --max-old-space-size=${CUSTOM_MAX_OLD_SPACE_SIZE:-460} src/index.js","npm_package_devDependencies__stryker_mutator_core":"^2.0.2","npm_config_editor":"vi","npm_config_rollback":"true","npm_config_tag_version_prefix":"v","npm_package_scripts_lint_fix":"eslint ./src --ext .js --fix","npm_config_cache_max":"Infinity","npm_config_timing":"","npm_config_userconfig":"/root/.npmrc","npm_package_contributors_0_email":"Oleksandr.Smorodin@dazn.com","npm_package_dependencies_compression":"^1.7.3","npm_package_dependencies_moment":"^2.24.0","npm_package_devDependencies_nyc":"^14.1.1","npm_config_engine_strict":"","npm_config_init_author_name":"","npm_config_init_author_url":"","npm_config_preid":"","npm_config_tmp":"/tmp","npm_package_description":"Service DCB","npm_package_contributors_1_email":"Joao.Henrique-Silva@dazn.com","npm_package_dependencies__hapi_joi":"^15.1.0","npm_package_dependencies_json_refs":"^3.0.13","npm_package_dependencies_swagger_mock_validator":"^7.0.0","npm_config_depth":"Infinity","npm_config_package_lock_only":"","npm_config_save_dev":"","npm_config_usage":"","npm_package_contributors_2_email":"Vasily.Gorin@dazn.com","npm_package_readmeFilename":"README.md","npm_package_homepage":"https://github.com/getndazn/service-dcb-web-api#readme","npm_config_metrics_registry":"https://registry.npmjs.org/","npm_config_cafile":"","npm_config_otp":"","npm_config_package_lock":"true","npm_config_progress":"true","npm_config_https_proxy":"","npm_config_save_prod":"","npm_package_contributors_3_email":"Marta.Fernandes@dazn.com","npm_package_scripts_docker_build":"docker build -t massive/node-template .","npm_config_audit":"true","npm_config_cidr":"","npm_config_onload_script":"","npm_config_sso_type":"oauth","npm_package_devDependencies_eslint_plugin_import":"^2.16.0","npm_config_rebuild_bundle":"true","npm_config_save_bundle":"","npm_config_shell":"bash","_":"/usr/local/bin/npm","npm_package_dependencies_express":"^4.16.4","npm_config_dry_run":"","npm_config_prefix":"/usr/local","npm_package_scripts_lint":"eslint ./src --ext .js","npm_package_dependencies_newrelic":"^5.6.0","npm_package_devDependencies__stryker_mutator_javascript_mutator":"^2.0.2","npm_config_scope":"","npm_config_browser":"","npm_config_cache_lock_wait":"10000","npm_config_ignore_prepublish":"","npm_config_registry":"https://registry.npmjs.org/","npm_config_save_optional":"","npm_config_searchopts":"","npm_config_versions":"","TERM":"xterm","npm_config_cache":"/root/.npm","npm_config_proxy":"","npm_config_send_metrics":"","npm_package_scripts_start":"node --max-old-space-size=${CUSTOM_MAX_OLD_SPACE_SIZE:-460} src/index.js","npm_package_scripts_start_win":"node --max-old-space-size=460 src/index.js","npm_config_global_style":"","npm_config_ignore_scripts":"","npm_config_version":"","npm_package_author_email":"bruno.germano@massive.co","npm_package_dependencies_axios":"^0.19.0","npm_package_devDependencies_shx":"^0.3.2","npm_config_local_address":"","npm_config_viewer":"man","npm_config_node_gyp":"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js","PATH":"/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","npm_package_name":"service-dcb-web-api","npm_package_repository_type":"git","npm_package_devDependencies__pact_foundation_pact":"^9.1.1","npm_config_audit_level":"low","npm_config_prefer_offline":"","NODE":"/usr/local/bin/node","npm_package_scripts_docker_run":"docker run -dP massive/node-template","npm_package_scripts_docker_compose_up":"docker-compose up","npm_package_scripts_test_integration":"npm test -- --testMatch '**/test/integration/**spec.js' --passWithNoTests","npm_package_dependencies__perform_middleware_common_trackers":"^1.0.2","npm_package_devDependencies_eslint_config_airbnb_base":"^13.1.0","npm_config_color":"true","npm_config_sign_git_commit":"","npm_package_scripts_test_unit":"npm test -- --testMatch '**/test/unit/**/*.spec.js'","npm_package_scripts_pact_contract":"CONFIG_ENV=pact NODE_ENV=pactTest jest --testMatch '**/test/pact/**/service.test.pact.js' --runInBand","npm_config_fetch_retry_mintimeout":"10000","npm_config_maxsockets":"50","npm_config_offline":"","npm_config_sso_poll_frequency":"500","npm_package_devDependencies__stryker_mutator_html_reporter":"^2.0.2","npm_package_devDependencies_eslint":"^5.15.1","npm_config_umask":"0022","npm_package_contributors_0_name":"Oleksandr Smodorin","npm_package_dependencies_aws_sdk":"^2.422.0","npm_package_devDependencies_supertest":"^3.4.2","npm_package_gitHead":"35bd2c8089fc22e415f0e406c30d17c4651b1a94","npm_config_fetch_retry_maxtimeout":"60000","npm_config_loglevel":"notice","npm_config_logs_max":"10","npm_config_message":"%s","npm_lifecycle_script":"CONFIG_ENV=pact NODE_ENV=pactTest jest --testMatch '**/test/pact/**/service.test.pact.js' --runInBand","npm_package_contributors_1_name":"Joao Machado Silva","npm_package_scripts_test":"CONFIG_ENV=testing jest","npm_package_dependencies_body_parser":"^1.18.3","npm_config_ca":"","npm_config_cert":"","npm_config_global":"","npm_config_link":"","npm_package_version":"0.6.0","npm_package_contributors_2_name":"Vasily Gorin","npm_package_repository_url":"git+https://github.com/getndazn/service-dcb-web-api.git","npm_package_scripts_test_mutation":"CONFIG_ENV=testing stryker run","npm_package_dependencies_jest":"^24.9.0","npm_config_access":"","npm_config_also":"","npm_config_save":"true","npm_config_unicode":"","npm_lifecycle_event":"pact:contract","npm_package_contributors_3_name":"Marta Fernandes","npm_package_dependencies_cors":"^2.8.5","npm_package_dependencies_js_yaml":"^3.13.1","npm_package_dependencies_jwks_rsa":"^1.5.1","npm_package_dependencies_uuid":"^3.3.2","npm_config_argv":"{\"remain\":[],\"cooked\":[\"run\",\"pact:contract\"],\"original\":[\"run\",\"pact:contract\"]}","npm_config_long":"","npm_config_production":"","npm_config_searchlimit":"20","npm_config_unsafe_perm":"","npm_config_update_notifier":"true","npm_package_scripts_test_coverage":"npm run test:all -- --coverage","npm_package_dependencies_lodash":"^4.17.15","npm_package_devDependencies_chai_as_promised":"^7.1.1","npm_config_auth_type":"legacy","npm_config_node_version":"10.15.3","npm_config_tag":"latest","npm_package_devDependencies_nock":"^11.3.3","npm_config_git_tag_version":"true","npm_config_commit_hooks":"true","npm_config_script_shell":"","npm_config_shrinkwrap":"true","npm_package_devDependencies__pact_foundation_pact_node":"^9.0.4","npm_config_fetch_retry_factor":"10","npm_config_save_exact":"","npm_config_strict_ssl":"true","npm_config_dev":"","npm_config_globalconfig":"/usr/local/etc/npmrc","npm_config_init_module":"/root/.npm-init.js","npm_config_parseable":"","PWD":"/tmp","npm_config_globalignorefile":"/usr/local/etc/npmignore","npm_execpath":"/usr/local/lib/node_modules/npm/bin/npm-cli.js","npm_package_author_name":"Bruno Germano","npm_config_cache_lock_retries":"10","npm_config_searchstaleness":"900","npm_config_node_options":"","npm_config_save_prefix":"^","npm_config_scripts_prepend_node_path":"warn-only","npm_package_dependencies_jsonwebtoken":"^8.5.1","npm_config_group":"","npm_config_init_author_email":"","npm_config_searchexclude":"","npm_package_scripts_pact_publish":"node test/scripts/publishPact.js","npm_config_git":"git","npm_config_optional":"true","NODE_ENV":"pactTest","npm_config_json":"","INIT_CWD":"/tmp","JEST_WORKER_ID":"1"}}'
[2019-09-16T13:58:12.605Z]  INFO: pact-node@9.0.4/19 on d5090416df14: Created './standalone/linux-x64-1.70.2/bin/pact-mock-service service --consumer 'service-consumer' --pact_dir '/tmp/test/pact/contracts' --host '127.0.0.1' --log '/tmp/test/pact/logs/pact-service-provider.log' --pact-file-write-mode 'overwrite' --port '9090' --provider 'service-provider' --pact_specification_version '2'' process with PID: 32
[2019-09-16T13:58:12.616Z] DEBUG: pact-node@9.0.4/19 on d5090416df14:
    /bin/sh: 1: ./standalone/linux-x64-1.70.2/bin/pact-mock-service: not found

[2019-09-16T13:58:12.616Z] ERROR: pact-node@9.0.4/19 on d5090416df14:
    Pact Binary Error: /bin/sh: 1: ./standalone/linux-x64-1.70.2/bin/pact-mock-service: not found

[2019-09-16T13:58:12.626Z]  WARN: pact-node@9.0.4/19 on d5090416df14: Pact exited with code 127.
[2019-09-16T13:58:12.626Z]  INFO: pact-node@9.0.4/19 on d5090416df14: Removing Pact with PID: 32
 FAIL  test/pact/service.test.pact.js (32.579s)
  When service is our Provider
    ✕ returns 200 from our service with the right response body (23ms)

  ● When service is our Provider › returns 200 from our service with the right response body

    Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● When service is our Provider › returns 200 from our service with the right response body

    TypeError: Cannot read property 'addInteraction' of undefined

      32 |
      33 |     test('returns 200 from our service with the right response body', async () => {
    > 34 |         await provider.addInteraction({
         |                        ^
      35 |             uponReceiving: 'a POST request to /v1/user',
      36 |             withRequest: {
      37 |                 method: 'POST',

      at Pact.Object.<anonymous>.Pact.addInteraction (node_modules/@pact-foundation/src/httpPact.ts:102:29)
      at Object.addInteraction (test/pact/service.test.pact.js:34:24)

  ● When service is our Provider › returns 200 from our service with the right response body

    TypeError: Cannot read property 'verify' of undefined

      24 |
      25 |     afterEach(async () => {
    > 26 |         await provider.verify();
         |                        ^
      27 |     });
      28 |
      29 |     afterAll(async () => {

      at Pact.Object.<anonymous>.Pact.verify (node_modules/@pact-foundation/src/httpPact.ts:113:8)
      at Object.verify (test/pact/service.test.pact.js:26:24)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        32.785s
```

**Comment by TimothyJones** [comment]
This is great detail, thanks. 

It’s just after midnight here, so I might be mistaken, but it looks like the path for the standalone isn’t correct (it should be inside node_modules).

I took a close read of the diff between 9.0.3 and 9.0.4, and I can’t immediately see the cause, but I did notice some dead code related to paths that we should remove.

I’ll have a closer look tomorrow.

Sent from my mobile

**Comment by vbotay** [comment]
Have to investigate it deeper. Now I face this issue on 9.0.3 as well, and I managed to run it without any problem on 9.0.4. 
It looks that problem hidden somewhere else.

**Comment by TimothyJones** [comment]
Is it a permissions issue? I have run in to weirdness with docker and executing files through node/npm before

**Comment by mefellows** [comment]
What's you host OS? It looks like you're installing pact on the host first and then running in docker. This will cause issues because Pact has platform specific code in it. You can't volume mount node_modules in this instance (i.e. run `npm install` in container)

**Comment by mefellows** [comment]
The path looks correct, it's relative to the pact-node dependencies path which is within node_modules.

**Comment by vbotay** [comment]
It's definitely related to docker. It's done automatically in container during pipeline execution and I was surprised when it stoped working without any changes. 
I think I have to find some issue in different place and it is not a problem of pact. 
Sorry for bothering you guys and thank you for fast responses.

**Comment by mefellows** [comment]
No worries and you're welcome!
