### ISSUE TITLE
Pact mock server not closing after timeout exceeded

### ISSUE THREAD

**Issue by basickarl** [pact-foundation/pact-node#192]
## Software versions

ubuntu 14.04
pact-node@9.0.4
node 10.16.3

## Expected behavior

Mock server close down after jamming and pressing ctrl-c to close the process

## Actual behavior

Jams, doesn't end, next time starting up test it complains about the port already being used (previous mock server does not shut down).

## Steps to reproduce

Set timeout to a small value for the consumer tests, e.g.
```
this.timeout(1);
```
Then run the consumer test.

## Relevant log files

```
> npx cross-env s_g_NODE_ENV=test mocha "_build/test/contract/**/*.consumer.spec.js"

Loaded /home/karl/dev/s-g/config/test.json configuration file
Config lib initialized
[2019-10-22T09:27:18.568Z]  INFO: pact-node@9.0.4/11823 on karl-Dell-Precision-M3800: 
    Creating Pact Server with options: 
    {"consumer":"s g","cors":false,"dir":"/home/karl/dev/s-g/_pacts","host":"127.0.0.1","log":"/home/karl/dev/s-g/log/pact-consumer.log","pactFileWriteMode":"overwrite","port":8080,"provider":"s g Test Module","spec":2,"ssl":false}


  Consumer contract test
    example
[2019-10-22T09:27:18.586Z] DEBUG: pact-node@9.0.4/11823 on karl-Dell-Precision-M3800: Starting pact binary with '/bin/sh,-c,./standalone/linux-x64-1.70.2/bin/pact-mock-service service --consumer 's g' --pact_dir '/home/karl/dev/s-g/_pacts' --host '127.0.0.1' --log '/home/karl/dev/s-g/log/pact-consumer.log' --pact-file-write-mode 'overwrite' --port '8080' --provider 's g Test Module' --pact_specification_version '2',{"cwd":"/home/karl/dev/s-g/node_modules/@pact-foundation/pact-node","detached":true,"env":{"LESSOPEN":"| /usr/bin/lesspipe %s","npm_package_scripts_start_db":"docker start db","npm_package_devDependencies__types_node":"12.0.0","npm_package_devDependencies_ts_node":"8.2.0","npm_config_cache_lock_stale":"60000","npm_config_ham_it_up":"","npm_config_legacy_bundling":"","npm_config_sign_git_tag":"","USER":"karl","LANGUAGE":"en_US","GTK_CSD":"1","LC_TIME":"sv_SE.UTF-8","npm_package_scripts_run_mq":"docker run -p 1883:1883 -p 8888:8888 -p 8081:8080 --name mqtt -d eclipse-mosquitto:1.6.4","npm_config_user_agent":"npm/6.9.0 node/v10.16.0 linux x64","npm_config_always_auth":"","XDG_SEAT":"seat0","npm_package_scripts_setup_db":"mongo s-g ./scripts/setup_db.js","npm_config_bin_links":"true","npm_config_key":"","SSH_AGENT_PID":"1777","XDG_SESSION_TYPE":"x11","npm_package_scripts_pull_db":"docker pull mongo:4.0","npm_package_devDependencies_nodemon":"1.19.0","npm_package_dependencies_mqtt":"2.18.8","npm_config_description":"true","npm_config_fetch_retries":"2","npm_config_heading":"npm","npm_config_init_version":"1.0.0","npm_config_user":"1000","npm_config_allow_same_version":"","npm_config_if_present":"","npm_node_execpath":"/home/karl/.nvm/versions/node/v10.16.0/bin/node","SHLVL":"2","npm_config_prefer_online":"","npm_config_noproxy":"","CHROME_DESKTOP":"code-url-handler.desktop","HOME":"/home/karl","npm_package_scripts_kill":"npm run __kill","npm_package_devDependencies__typescript_eslint_parser":"1.9.0","npm_package_devDependencies_mocha":"6.1.4","npm_config_force":"","TERM_PROGRAM_VERSION":"1.38.1","DESKTOP_SESSION":"pantheon","NVM_BIN":"/home/karl/.nvm/versions/node/v10.16.0/bin","npm_package_devDependencies__types_ws":"6.0.1","npm_package_devDependencies_eslint_config_prettier":"4.2.0","npm_package_devDependencies_run_script_os":"1.0.5","npm_config_only":"","npm_config_read_only":"","QT_STYLE_OVERRIDE":"gtk","GIO_LAUNCHED_DESKTOP_FILE":"/usr/share/applications/code.desktop","npm_config_cache_min":"10","npm_config_init_license":"ISC","QT_LINUX_ACCESSIBILITY_ALWAYS_ON":"1","GTK_MODULES":"pantheon-filechooser-module","XDG_SEAT_PATH":"/org/freedesktop/DisplayManager/Seat0","npm_config_editor":"vi","npm_config_rollback":"true","npm_config_tag_version_prefix":"v","LC_MONETARY":"sv_SE.UTF-8","npm_config_cache_max":"Infinity","npm_config_userconfig":"/home/karl/.npmrc","npm_config_timing":"","DBUS_SESSION_BUS_ADDRESS":"unix:abstract=/tmp/dbus-TBaAEPV28W,guid=2d3b1f7f6e4bff87b7c463ec5da81828","npm_package_devDependencies_nyc":"14.1.1","npm_config_tmp":"/tmp","npm_config_engine_strict":"","npm_config_init_author_name":"","npm_config_init_author_url":"","npm_config_preid":"","GIO_LAUNCHED_DESKTOP_FILE_PID":"3763","COLORTERM":"truecolor","npm_package_description":"s-g application","npm_package_devDependencies_typescript":"3.4.5","npm_config_depth":"Infinity","npm_config_package_lock_only":"","npm_config_save_dev":"","npm_config_usage":"","NVM_DIR":"/home/karl/.nvm","npm_package_scripts_verify_and_install":"npm cache verify && npm install","npm_package_scripts_stop_db":"docker stop db","npm_package_scripts_devt":"npm run dev__unit_test","npm_package_readmeFilename":"README.md","npm_config_metrics_registry":"https://registry.npmjs.org/","npm_config_package_lock":"true","npm_config_progress":"true","npm_config_cafile":"","npm_config_otp":"","npm_config_https_proxy":"","npm_config_save_prod":"","MANDATORY_PATH":"/usr/share/gconf/pantheon.mandatory.path","npm_package_scripts_docker_build":"npm run __docker_build","npm_package_scripts_dev":"npm run dev__app_and_unit_test","npm_package_devDependencies_prettier":"1.17.0","npm_config_audit":"true","npm_config_sso_type":"oauth","npm_config_cidr":"","npm_config_onload_script":"","LOGNAME":"karl","npm_package_scripts_style_fix":"npx prettier --write \"**/*.ts\" --write \"**/*.json\" --write \"**/*.js\"","npm_package_scripts_clean":"npx shx rm -rf ./_build ./_coverage/ ./_coverage/ ./_cypress/ ./_nyc_output/ ./_results/ ./_results/","npm_package_dependencies_request":"2.88.0","npm_config_rebuild_bundle":"true","npm_config_shell":"/bin/bash","npm_config_save_bundle":"","_":"/home/karl/.nvm/versions/node/v10.16.0/bin/npm","npm_package_dependencies_express":"4.16.4","npm_config_prefix":"/home/karl/.nvm/versions/node/v10.16.0","npm_config_dry_run":"","DEFAULTS_PATH":"/usr/share/gconf/pantheon.default.path","npm_package_scripts_run_db":"docker run --name db -d -p 27017:27017 mongo:4.0","npm_package_scripts_lint":"npx eslint . --ext js,ts,json","npm_package_devDependencies__typescript_eslint_eslint_plugin":"1.9.0","npm_config_scope":"","npm_config_cache_lock_wait":"10000","npm_config_registry":"https://registry.npmjs.org/","npm_config_browser":"","npm_config_ignore_prepublish":"","npm_config_save_optional":"","npm_config_searchopts":"","npm_config_versions":"","XDG_SESSION_ID":"c2","TERM":"xterm-256color","npm_package_scripts_dev__app":"npx cross-env s_g_NODE_ENV=development nodemon --config ./nodemon.app.json","npm_package_dependencies_ws":"7.0.0","npm_config_cache":"/home/karl/.npm","npm_config_proxy":"","npm_config_send_metrics":"","GNOME_DESKTOP_SESSION_ID":"this-is-deprecated","npm_package_scripts_start":"npm run build && npx cross-env s_g_NODE_ENV=development node ./_build/application/server.js","npm_config_global_style":"","npm_config_ignore_scripts":"","npm_config_version":"","npm_package_author_email":"karl.morrison.ext@adbsafegate.com","npm_package_devDependencies__types_mocha":"5.2.7","npm_package_devDependencies_shx":"0.3.2","npm_package_dependencies_request_promise_native":"1.0.7","npm_config_viewer":"man","npm_config_node_gyp":"/home/karl/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js","npm_config_local_address":"","PATH":"/home/karl/dev/s-g/node_modules/.bin:/home/karl/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/karl/dev/s-g/node_modules/.bin:/home/karl/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/karl/dev/s-g/node_modules/.bin:/home/karl/bin:/home/karl/.local/bin:/home/karl/.nvm/versions/node/v10.16.0/bin:/home/karl/bin:/home/karl/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games","SESSION_MANAGER":"local/karl-Dell-Precision-M3800:@/tmp/.ICE-unix/1695,unix/karl-Dell-Precision-M3800:/tmp/.ICE-unix/1695","GDM_LANG":"en_US","NODE":"/home/karl/.nvm/versions/node/v10.16.0/bin/node","npm_package_name":"s-g","npm_package_scripts_provider_test":"npm run build && npm run __provider_test__start_app_and_test","npm_package_repository_type":"git","npm_package_devDependencies__pact_foundation_pact":"9.1.1","npm_package_dependencies_cross_env":"5.2.0","npm_config_audit_level":"low","npm_config_prefer_offline":"","LC_ADDRESS":"sv_SE.UTF-8","XDG_MENU_PREFIX":"gnome-","XDG_SESSION_PATH":"/org/freedesktop/DisplayManager/Session0","XDG_RUNTIME_DIR":"/run/user/1000","npm_package_scripts_style":"npx prettier --check \"**/*.ts\" --check \"**/*.json\" --check \"**/*.js\"","npm_package_scripts_consumer_test":"npm run build && npm run __consumer_test__start_test","npm_config_color":"true","npm_config_sign_git_commit":"","DISPLAY":":0","npm_package_scripts_unit_test":"npx shx rm -rf ./_nyc_output ./_coverage ./_results && npm run build && npx cross-env s_g_NODE_ENV=test nyc --nycrc-path=./.nycrc.json mocha \"./_build/test/unit/**/*.spec.js\" --reporter mocha-multi-reporters --reporter-options configFile=reporter.config.json","npm_config_fetch_retry_mintimeout":"10000","npm_config_maxsockets":"50","npm_config_sso_poll_frequency":"500","npm_config_offline":"","LC_TELEPHONE":"sv_SE.UTF-8","LANG":"en_US.UTF-8","XDG_CURRENT_DESKTOP":"Unity","npm_package_scripts_start_mq":"docker start mq","npm_package_scripts_dev__app_and_unit_test":"npx cross-env s_g_NODE_ENV=development nodemon --config ./nodemon.app.unit.test.json","npm_package_devDependencies_eslint":"5.16.0","npm_package_devDependencies_eslint_plugin_json":"1.4.0","npm_package_devDependencies_eslint_plugin_mocha":"5.3.0","npm_package_dependencies_winston":"3.2.1","npm_config_umask":"0002","TERM_PROGRAM":"vscode","LS_COLORS":"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:","XMODIFIERS":"@im=ibus","XDG_SESSION_DESKTOP":"pantheon","XAUTHORITY":"/home/karl/.Xauthority","npm_package_scripts_dev__unit_test":"npx cross-env s_g_NODE_ENV=development nodemon --config ./nodemon.unit.test.json","npm_package_gitHead":"d1a65827f9eaf4e421d44134753c724899e49270","npm_config_fetch_retry_maxtimeout":"60000","npm_config_loglevel":"notice","npm_config_logs_max":"10","npm_config_message":"%s","npm_lifecycle_script":"npx cross-env s_g_NODE_ENV=test mocha \"_build/test/contract/**/*.consumer.spec.js\"","XDG_GREETER_DATA_DIR":"/var/lib/lightdm-data/karl","SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","GSETTINGS_SCHEMA_DIR":"/home/karl/data","npm_config_ca":"","npm_config_cert":"","npm_config_global":"","npm_config_link":"","SHELL":"/bin/bash","LC_NAME":"sv_SE.UTF-8","npm_package_version":"0.1.0","npm_package_repository_url":"git@ssh.dev.azure.com:v3/adbsg/s-g/s-g","npm_config_save":"true","npm_config_unicode":"true","npm_config_access":"","npm_config_also":"","npm_lifecycle_event":"__consumer_test__start_test","QT_ACCESSIBILITY":"1","GDMSESSION":"pantheon","NO_AT_BRIDGE":"1","npm_package_scripts_pull_mq":"docker pull eclipse-mosquitto:1.6.4","npm_package_scripts_build":"npx shx rm -rf _build && npx tsc","npm_config_argv":"{\"remain\":[],\"cooked\":[\"run\",\"__consumer_test__start_test\"],\"original\":[\"run\",\"__consumer_test__start_test\"]}","npm_config_searchlimit":"20","npm_config_unsafe_perm":"true","npm_config_update_notifier":"true","npm_config_before":"","npm_config_long":"","npm_config_production":"","LESSCLOSE":"/usr/bin/lesspipe %s %s","npm_config_auth_type":"legacy","npm_config_node_version":"10.16.0","npm_config_tag":"latest","LC_MEASUREMENT":"sv_SE.UTF-8","npm_config_git_tag_version":"true","npm_config_commit_hooks":"true","npm_config_shrinkwrap":"true","npm_config_script_shell":"","LC_IDENTIFICATION":"sv_SE.UTF-8","npm_package_scripts_port":"npm run __port","npm_package_license":"TODO: Figure this out.","npm_package_devDependencies__pact_foundation_pact_node":"9.0.4","npm_package_devDependencies_start_server_and_test":"1.9.0","npm_package_dependencies_mongoose":"5.5.6","npm_config_fetch_retry_factor":"10","npm_config_strict_ssl":"true","npm_config_save_exact":"","XDG_VTNR":"7","QT_IM_MODULE":"ibus","npm_package_scripts_gen_config":"npx ts-node ./scripts/generate_config.js","npm_package_scripts_commit":"npm run lint && npm run style && npm run test","npm_config_globalconfig":"/home/karl/.nvm/versions/node/v10.16.0/etc/npmrc","npm_config_init_module":"/home/karl/.npm-init.js","npm_config_dev":"","npm_config_parseable":"","PWD":"/home/karl/dev/s-g","npm_package_scripts_deva":"npm run dev__app","npm_package_devDependencies_mocha_multi_reporters":"1.1.7","npm_config_globalignorefile":"/home/karl/.nvm/versions/node/v10.16.0/etc/npmignore","npm_execpath":"/home/karl/.nvm/versions/node/v10.16.0/lib/node_modules/npm/bin/npm-cli.js","NVM_CD_FLAGS":"","XDG_CONFIG_DIRS":"/etc/xdg/xdg-pantheon:/etc/xdg","XDG_DATA_DIRS":"/usr/share/pantheon:/usr/local/share/:/usr/share/","npm_package_scripts_i":"npm run verify_and_install && npm run pull_mq && npm run pull_db","npm_package_author_name":"Karl Morrison","npm_package_devDependencies_mocha_junit_reporter":"1.23.0","npm_config_cache_lock_retries":"10","npm_config_searchstaleness":"900","LC_NUMERIC":"sv_SE.UTF-8","npm_package_dependencies_convict":"5.0.0","npm_config_save_prefix":"^","npm_config_scripts_prepend_node_path":"warn-only","npm_config_node_options":"","LC_PAPER":"sv_SE.UTF-8","npm_config_group":"1000","npm_config_init_author_email":"","npm_config_searchexclude":"","npm_package_scripts_stop_mq":"docker stop mq","npm_config_git":"git","npm_config_optional":"true","INIT_CWD":"/home/karl/dev/s-g","npm_config_json":"","s_g_NODE_ENV":"test"}}'
[2019-10-22T09:27:18.600Z]  INFO: pact-node@9.0.4/11823 on karl-Dell-Precision-M3800: Created './standalone/linux-x64-1.70.2/bin/pact-mock-service service --consumer 's g' --pact_dir '/home/karl/dev/s-g/_pacts' --host '127.0.0.1' --log '/home/karl/dev/s-g/log/pact-consumer.log' --pact-file-write-mode 'overwrite' --port '8080' --provider 's g Test Module' --pact_specification_version '2'' process with PID: 11842
[2019-10-22T09:27:19.337Z] DEBUG: pact-node@9.0.4/11823 on karl-Dell-Precision-M3800: 
    INFO  WEBrick 1.3.1
    INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
    
[2019-10-22T09:27:19.338Z] DEBUG: pact-node@9.0.4/11823 on karl-Dell-Precision-M3800: 
    INFO  WEBrick::HTTPServer#start: pid=11843 port=8080
    
      1) "before all" hook for "should receive response with hello object"
      2) "after all" hook for "should receive response with hello object"


  0 passing (1s)
  2 failing

  1) Consumer contract test
       example
         "before all" hook for "should receive response with hello object":
     Error: Timeout of 1000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/karl/dev/s-g/_build/test/contract/example.consumer.spec.js)
  

  2) Consumer contract test
       example
         "after all" hook for "should receive response with hello object":
     TypeError: Cannot read property 'writePact' of undefined
      at Pact.finalize (node_modules/@pact-foundation/pact/httpPact.js:121:14)
      at Context.<anonymous> (_build/test/contract/example.consumer.spec.js:66:26)
      at Generator.next (<anonymous>)
      at /home/karl/dev/s-g/_build/test/contract/example.consumer.spec.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (_build/test/contract/example.consumer.spec.js:3:12)
      at Context.<anonymous> (_build/test/contract/example.consumer.spec.js:65:20)



[2019-10-22T09:27:19.628Z]  INFO: pact@9.1.1/11823 on karl-Dell-Precision-M3800: 
    Setting up Pact with Consumer "s g" and Provider "s g Test Module"
        using mock service on Port: "8080"
```
The log ending here is where it jams and sits until I need to close it.

Following is the log when trying to re-run the test, this log will always show no matter how many times I run it until I manually close the stuck mock server process:
```
> npx cross-env s_g_NODE_ENV=test mocha "_build/test/contract/**/*.consumer.spec.js"

Loaded /home/karl/dev/s-g/config/test.json configuration file
Config lib initialized
[2019-10-22T09:32:29.695Z]  INFO: pact-node@9.0.4/12903 on karl-Dell-Precision-M3800: 
    Creating Pact Server with options: 
    {"consumer":"s g","cors":false,"dir":"/home/karl/dev/s-g/_pacts","host":"127.0.0.1","log":"/home/karl/dev/s-g/log/pact-consumer.log","pactFileWriteMode":"overwrite","port":8080,"provider":"s g Test Module","spec":2,"ssl":false}


  Consumer contract test
    example
      1) "before all" hook for "should receive response with hello object"
      2) "after all" hook for "should receive response with hello object"


  0 passing (14ms)
  2 failing

  1) Consumer contract test
       example
         "before all" hook for "should receive response with hello object":
     Error: Port 8080 is unavailable on address 127.0.0.1
      at Server.<anonymous> (node_modules/@pact-foundation/pact/common/net.js:26:24)
      at emitErrorNT (net.js:1306:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  2) Consumer contract test
       example
         "after all" hook for "should receive response with hello object":
     TypeError: Cannot read property 'writePact' of undefined
      at Pact.finalize (node_modules/@pact-foundation/pact/httpPact.js:121:14)
      at Context.<anonymous> (_build/test/contract/example.consumer.spec.js:66:26)
      at Generator.next (<anonymous>)
      at /home/karl/dev/s-g/_build/test/contract/example.consumer.spec.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (_build/test/contract/example.consumer.spec.js:3:12)
      at Context.<anonymous> (_build/test/contract/example.consumer.spec.js:65:20)



[2019-10-22T09:32:29.714Z]  INFO: pact-node@9.0.4/12903 on karl-Dell-Precision-M3800: Removing all Pact servers.
```
(the "Removing all Pact servers.", if this means removing the mock servers then it does not)

Also the error messages to us developers are not the slightest bit handy.

**Comment by mefellows** [comment]
Thanks for the report, will look into this tomorrow.

There is an example in the pact js repo of programmatically ensuring all servers are shutdown on a process exit, this might be useful to consider using in the short term

**Comment by mefellows** [comment]
I tried adding a short timeout to the mocha example in the pact-js repository, and no mock server hangs around afterwards.

Can you please provide a short reproducible example for us to dig into?

![Screen Shot 2019-10-25 at 10 03 35 pm](https://user-images.githubusercontent.com/53900/67566423-7784c380-f773-11e9-901c-62d56e94ff3f.png)

**Comment by mefellows** [comment]
I tried adding a short timeout to the mocha example in the pact-js repository, and no mock server hangs around afterwards.

Can you please provide a short reproducible example for us to dig into?

![Screen Shot 2019-10-25 at 10 03 35 pm](https://user-images.githubusercontent.com/53900/67566423-7784c380-f773-11e9-901c-62d56e94ff3f.png)

**Comment by mefellows** [comment]
Were you able to reproduce this @basickarl ?

**Comment by basickarl** [comment]
@mefellows I unfortunately was not able to reproduce it since we moved to an asynchronous messaging architecture which doesn't start up a server like the REST approach. I'll close this and we'll hope noone else encounters it.

**Comment by mefellows** [comment]
No worries, thanks Karl
