### ISSUE TITLE
Connection Refused error when attempting to `createServer`

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-node#56]
Since upgrading to `5.2.x` I'm getting the following error when trying to run `createServer`. 

```
[2017-11-07T20:41:59.511Z]  INFO: pact-node@5.2.0/13140 on localhost:
    Creating Pact Server with options:
    host = 127.0.0.1,
    port = 9993,
    log = /Users/mfellows/development/public/pact-js/logs/mockserver-integration.log,
    dir = /Users/mfellows/development/public/pact-js/pacts,
    spec = 2,
    ssl = false,
    sslcert = ,
    sslkey = ,
    cors = false


  Integration
    Pact on http protocol
      1) "before all" hook
      2) "after all" hook

  0 passing (82ms)
  2 failing

  1) Integration Pact on http protocol "before all" hook:
     Uncaught TypeError: Cannot read property 'message' of null
      at Request._callback (/Users/mfellows/development/public/pact-js/node_modules/@pact-foundation/pact-node/src/server.ts:327:121)
      at Request.self.callback (/Users/mfellows/development/public/pact-js/node_modules/request/request.js:188:22)
      at emitTwo (events.js:125:13)
      at Request.emit (events.js:213:7)
      at Request.<anonymous> (/Users/mfellows/development/public/pact-js/node_modules/request/request.js:1171:10)
      at emitOne (events.js:115:13)
      at Request.emit (events.js:210:7)
      at IncomingMessage.<anonymous> (/Users/mfellows/development/public/pact-js/node_modules/request/request.js:1091:12)
      at Object.onceWrapper (events.js:314:30)
      at emitNone (events.js:110:20)
      at IncomingMessage.emit (events.js:207:7)
      at endReadableNT (_stream_readable.js:1047:12)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickCallback (internal/process/next_tick.js:161:9)

  2) Integration Pact on http protocol "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:9993
      at Object.exports._errnoException (util.js:1016:11)
      at exports._exceptionWithHostPort (util.js:1039:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
```

The issue seemingly can be traced back to the following [line](src/server.ts:327:121) related to waiting for the server to start:

```
http(config, (err, res) => (!err && res.statusCode === 200) ? deferred.resolve() : deferred.reject(`HTTP Error: '${err.message}'`));
```

In the rejection path, `err` may be `null` (in this case it is) and that crashes the entire promise chain, bailing out of any retry logic and recovering when the service is up. Temporarily removing the `.message` resolves the issue entirely.

I need to do more to dig into this, but creating this as a scratchpad for my findings.

**Comment by mefellows** [comment]
Confirming that running the following (converted from TS -> JS) results in an issue:

```js
import pact from "@pact-foundation/pact-node";
const server = pact.createServer({port: 9999});
server.start().then(() => {
	// Do your testing/development here
	console.log('pacty yayay')
});
```

Output:

```
matt /tmp λ node index.js
[2017-11-07T22:13:21.823Z]  INFO: pact-node@5.2.0/17896 on localhost:
    Creating Pact Server with options:
    port = 9999,
    ssl = false,
    cors = false,
    dir = /private/tmp,
    host = localhost
[2017-11-07T22:13:21.830Z]  INFO: pact-node@5.2.0/17896 on localhost: Creating Pact with PID: 17897
[2017-11-07T22:13:21.860Z]  INFO: pact-node@5.2.0/17896 on localhost: Removing all Pact servers.
[2017-11-07T22:13:21.860Z]  INFO: pact-node@5.2.0/17896 on localhost: Removing Pact with PID: 17897
/private/tmp/node_modules/@pact-foundation/pact-node/src/server.js:286
        http(config, function (err, res) { return (!err && res.statusCode === 200) ? deferred.resolve() : deferred.reject("HTTP Error: '" + err.message + "'"); });
                                                                                                                                               ^

TypeError: Cannot read property 'message' of null
    at Request._callback (/private/tmp/node_modules/@pact-foundation/pact-node/src/server.js:286:144)
    at Request.self.callback (/private/tmp/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/private/tmp/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/private/tmp/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
matt /tmp λ
```

Here's my dependency tree:

```
matt /tmp λ npm list
tmp@1.0.0 /private/tmp
└─┬ @pact-foundation/pact-node@5.2.0
  ├─┬ @pact-foundation/pact-standalone@1.1.4
  │ ├── bunyan@1.8.12 deduped
  │ └── bunyan-prettystream@0.1.3 deduped
  ├─┬ bunyan@1.8.12
  │ ├─┬ dtrace-provider@0.8.5
  │ │ └── nan@2.7.0
  │ ├── moment@2.19.1
  │ ├─┬ mv@2.1.1
  │ │ ├── mkdirp@0.5.1 deduped
  │ │ ├── ncp@2.0.0
  │ │ └─┬ rimraf@2.4.5
  │ │   └─┬ glob@6.0.4
  │ │     ├─┬ inflight@1.0.6
  │ │     │ ├── once@1.4.0 deduped
  │ │     │ └── wrappy@1.0.2
  │ │     ├── inherits@2.0.3 deduped
  │ │     ├─┬ minimatch@3.0.4
  │ │     │ └─┬ brace-expansion@1.1.8
  │ │     │   ├── balanced-match@1.0.0
  │ │     │   └── concat-map@0.0.1
  │ │     ├─┬ once@1.4.0
  │ │     │ └── wrappy@1.0.2 deduped
  │ │     └── path-is-absolute@1.0.1
  │ └── safe-json-stringify@1.0.4
  ├── bunyan-prettystream@0.1.3
  ├── check-types@7.3.0
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├── q@1.5.0
  ├─┬ request@2.81.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.6.0
  │ ├── caseless@0.12.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.1
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@2.1.4
  │ │ ├── asynckit@0.4.0
  │ │ ├── combined-stream@1.0.5 deduped
  │ │ └── mime-types@2.1.17 deduped
  │ ├─┬ har-validator@4.2.1
  │ │ ├─┬ ajv@4.11.8
  │ │ │ ├── co@4.6.0
  │ │ │ └─┬ json-stable-stringify@1.0.1
  │ │ │   └── jsonify@0.0.0
  │ │ └── har-schema@1.0.5
  │ ├─┬ hawk@3.1.3
  │ │ ├─┬ boom@2.10.1
  │ │ │ └── hoek@2.16.3 deduped
  │ │ ├─┬ cryptiles@2.0.5
  │ │ │ └── boom@2.10.1 deduped
  │ │ ├── hoek@2.16.3
  │ │ └─┬ sntp@1.0.9
  │ │   └── hoek@2.16.3 deduped
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.4.1
  │ │ │ ├── assert-plus@1.0.0
  │ │ │ ├── extsprintf@1.3.0
  │ │ │ ├── json-schema@0.2.3
  │ │ │ └─┬ verror@1.10.0
  │ │ │   ├── assert-plus@1.0.0
  │ │ │   ├── core-util-is@1.0.2 deduped
  │ │ │   └── extsprintf@1.3.0 deduped
  │ │ └─┬ sshpk@1.13.1
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├─┬ bcrypt-pbkdf@1.0.1
  │ │   │ └── tweetnacl@0.14.5 deduped
  │ │   ├─┬ dashdash@1.14.1
  │ │   │ └── assert-plus@1.0.0
  │ │   ├─┬ ecc-jsbn@0.1.1
  │ │   │ └── jsbn@0.1.1 deduped
  │ │   ├─┬ getpass@0.1.7
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── jsbn@0.1.1
  │ │   └── tweetnacl@0.14.5
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.17
  │ │ └── mime-db@1.30.0
  │ ├── oauth-sign@0.8.2
  │ ├── performance-now@0.2.0
  │ ├── qs@6.4.0
  │ ├── safe-buffer@5.1.1
  │ ├── stringstream@0.0.5
  │ ├─┬ tough-cookie@2.3.3
  │ │ └── punycode@1.4.1
  │ ├─┬ tunnel-agent@0.6.0
  │ │ └── safe-buffer@5.1.1 deduped
  │ └── uuid@3.1.0
  ├─┬ traverson@6.0.3
  │ ├── jsonpath-plus@0.16.0
  │ ├─┬ minilog@3.1.0
  │ │ └── microee@0.0.6
  │ ├── request@2.81.0 deduped
  │ ├── resolve-url@0.2.1
  │ ├─┬ superagent@3.8.0
  │ │ ├── component-emitter@1.2.1
  │ │ ├── cookiejar@2.1.1
  │ │ ├─┬ debug@3.1.0
  │ │ │ └── ms@2.0.0
  │ │ ├── extend@3.0.1 deduped
  │ │ ├─┬ form-data@2.3.1
  │ │ │ ├── asynckit@0.4.0 deduped
  │ │ │ ├── combined-stream@1.0.5 deduped
  │ │ │ └── mime-types@2.1.17 deduped
  │ │ ├── formidable@1.1.1
  │ │ ├── methods@1.1.2
  │ │ ├── mime@1.4.1
  │ │ ├── qs@6.5.1
  │ │ └─┬ readable-stream@2.3.3
  │ │   ├── core-util-is@1.0.2
  │ │   ├── inherits@2.0.3
  │ │   ├── isarray@1.0.0
  │ │   ├── process-nextick-args@1.0.7
  │ │   ├── safe-buffer@5.1.1 deduped
  │ │   ├─┬ string_decoder@1.0.3
  │ │   │ └── safe-buffer@5.1.1 deduped
  │ │   └── util-deprecate@1.0.2 deduped
  │ ├─┬ underscore.string@3.3.4
  │ │ ├── sprintf-js@1.1.1
  │ │ └── util-deprecate@1.0.2
  │ └── url-template@2.0.8
  ├─┬ traverson-hal@6.0.0
  │ └── halfred@1.0.0
  ├─┬ traverson-promise@0.0.9
  │ ├── bluebird@3.5.1
  │ └── traverson@6.0.3 deduped
  ├── underscore@1.8.3
  ├─┬ unixify@1.0.0
  │ └─┬ normalize-path@2.1.1
  │   └── remove-trailing-separator@1.1.0
  └── url-join@2.0.2

```
