### ISSUE TITLE
npm install @pact-foundation/pact-node fails: Cannot find module 'rimraf'

### ISSUE THREAD

**Issue by argos83** [pact-foundation/pact-node#82]
Installation of pact-node fails since version 6.12.0 if `rimraf` has not been previously installed.

Tested with Node versions:
  * 4.8.7
  * 6.13.0
  * 8.9.4

On macOS High Sierra

**Steps to reproduce**: 
  Execute `@pact-foundation/pact-node@6.12.2` on a clean node environment (i.e. no node modules installed)

```
$ npm install @pact-foundation/pact-node@6.12.2

....


gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp

> spawn-sync@1.0.15 postinstall /Users/********/node_modules/spawn-sync
> node postinstall


> caporal@0.10.0 postinstall /Users/********/node_modules/caporal
> (test -f ./node_modules/husky/bin/install.js && node ./node_modules/husky/bin/install.js) || exit 0


> @pact-foundation/pact-node@6.12.0 postinstall /Users/********/node_modules/@pact-foundation/pact-node
> node postinstall.js

module.js:540
    throw err;
    ^

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp

> spawn-sync@1.0.15 postinstall /Users/********/node_modules/spawn-sync
> node postinstall


> caporal@0.10.0 postinstall /Users/stello/git/contract-testing-cli/node_modules/caporal
> (test -f ./node_modules/husky/bin/install.js && node ./node_modules/husky/bin/install.js) || exit 0


> @pact-foundation/pact-node@6.12.2 postinstall /Users/********/node_modules/@pact-foundation/pact-node
> node postinstall.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/**********/node_modules/@pact-foundation/pact-node/standalone/install.js:10:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pact-foundation/pact-node@6.12.2 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @pact-foundation/pact-node@6.12.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Seems that your installation scripts rely on `rimraf` which is only declared as a devDependency.

**Workaround**:
 
Execute `npm install rimraf` first.

**Comment by mboudreau** [comment]
Crap, thought I had removed rimraf from the code.  Fixing now.

**Comment by BenSayers** [comment]
Thanks for fixing this so quickly @mboudreau!

**Comment by argos83** [comment]
Thanks @mboudreau !

**Comment by mboudreau** [comment]
@argos83 @BenSayers You're very welcome.  It was my bad anyways :/

We already have a new version out with messaging support as well, 6.13.0.  Cheers.

**Comment by bethesque** [comment]
@BenSayers @argos83 the messaging code is just an alpha release. Don't jump the gun please @mboudreau!
