### ISSUE TITLE
No consumer contract parser found for hash

### ISSUE THREAD

**Issue by shavo007** [pact-foundation/pact-node#98]
Issue when verifying my pact 
sample code

```
const pact = require('@pact-foundation/pact-node')

const opts = {
	providerBaseUrl: 'http://my.api', // where your service will be running during the test, either staging or localhost on CI
	// providerStatesSetupUrl: 'http://localhost:3001/test/setup', // the url to call to set up states
	// pactUrls: ['http://localhost/'], // the pacts to test against
	// pactBrokerUsername: 'shanelee007',
	// pactBrokerPassword: 'xxx',
	publishVerificationResult: true,
	providerVersion: '2.0.0'
	provider: 'Talent%20API'
}

pact.verifyPacts(opts)
	.then(() => {
		console.log('success')
		process.exit(0)
	})
	.catch(error => {
		console.log('failed', error)
		process.exit(1)
	})

```

When i run this i was expecting to pull down all pacts for my provider. I am running the latest pact broker docker image

But i get the error above

Deps are:

```
    "@pact-foundation/pact": "5.9.1",
        "@pact-foundation/pact-node": "^6.19.4",
```

it only works when i hardcode the absolute url for the pact broker

```js
pactUrls: [
		'http://localhost/pacts/provider/Talent%20API/consumer/experienceAPI/latest'
	 ], // the pacts to test against
```

**Comment by mefellows** [comment]
Thanks @shavo007.

Could you please post the debug logs for this. You'll need to set the following in your test code:

```
var pact = require('@pact-foundation/pact-node');
pact.logLevel('debug');
```

As a start, you need to URL encode your provider name. i.e. 

```
provider: 'Talent%20API'
```

can simply be:

```
provider: 'Talent API'
```

**Comment by shavo007** [comment]
not a problem @mefellows 

config again:

```
const pact = require('@pact-foundation/pact-node')

pact.logLevel('debug')

const opts = {
    providerBaseUrl: 'http://talent.xxx', // where your service will be running during the test, either staging or localhost on CI
    // providerStatesSetupUrl: 'http://localhost:3001/test/setup', // the url to call to set up states
    pactUrls: ['http://localhost'], // the pacts to test against
    pactBrokerUsername: 'shanelee007',
    pactBrokerPassword: 'xxx',
    publishVerificationResult: true,
    providerVersion: '2.0.0',
    provider: 'Talent API'
}```

here is the error trace

```failed Error:node_modules/@pact-foundation/pact-node/standalone/darwin-1.47.2/lib/vendor/ruby/2.2.0/gems/pact-support-1.6.2/lib/pact/consumer_contract/consumer_contract.rb:44:in `from_hash': No consumer contract parser found for hash: {"_links"=>{"self"=>{"href"=>"http://localhost", "title"=>"Index", "templated"=>false}, "pb:publish-pact"=>{"href"=>"http://localhost/pacts/provider/{provider}/consumer/{consumer}/version/{consumerApplicationVersion}", "title"=>"Publish a pact", "templated"=>true}, "pb:latest-pact-versions"=>{"href"=>"http://localhost/pacts/latest", "title"=>"Latest pact versions", "templated"=>false}, "pb:pacticipants"=>{"href"=>"http://localhost/pacticipants", "title"=>"Pacticipants", "templated"=>false}, "pb:latest-provider-pacts"=>{"href"=>"http://localhost/pacts/provider/{provider}/latest", "title"=>"Latest pacts by provider", "templated"=>true}, "pb:latest-provider-pacts-with-tag"=>{"href"=>"http://localhost/pacts/provider/{provider}/latest/{tag}", "title"=>"Latest pacts for provider with the specified tag", "templated"=>true}, "pb:provider-pacts-with-tag"=>{"href"=>"http://localhost/pacts/provider/{provider}/tag/{tag}", "title"=>"All pact versions for the provider with the specified consumer version tag", "templated"=>true}, "pb:provider-pacts"=>{"href"=>"http://localhost/pacts/provider/{provider}", "title"=>"All pact versions for the specified provider", "templated"=>true}, "pb:latest-version"=>{"href"=>"http://localhost/pacticipants/{pacticipant}/latest-version", "title"=>"Latest pacticipant version", "templated"=>true}, "pb:latest-tagged-version"=>{"href"=>"http://localhost/pacticipants/{pacticipant}/latest-version/{tag}", "title"=>"Latest pacticipant version with the specified tag", "templated"=>true}, "pb:webhooks"=>{"href"=>"http://localhost/webhooks", "title"=>"Webhooks", "templated"=>false}, "curies"=>[{"name"=>"pb", "href"=>"http://localhost/doc/{rel}?context=index", "templated"=>true}]}} (Pact::Error)
	from node_modules/@pact-foundation/pact-node/standalone/darwin-1.47.2/lib/vendor/ruby/2.2.0/gems/pact-support-1.6.2/lib/pact/consumer_contract/consumer_contract.rb:49:in `from_json'
	from node_modules/@pact-foundation/pact-node/standalone/darwin-1.47.2/lib/vendor/ruby/2.2.0/gems/pact-1.28.0/lib/pact/provider/rspec.rb:26:in `honour_pactfile'
	from node_modules/@pact-foundation/pact-node/standalone/darwin-1.47.2/lib/vendor/ruby/2.2.0/gems/pact-1.28.0/lib/pact/provider/pact_spec_runner.rb:123:in `block in initialize_specs'
	from node_modules/@pact-foundation/pact-node/standalone/darwin-1.47.2/lib/vendor/ruby/2.2.0/gems/pact-1.28.0/lib/pact/provider/pact_spec_runner.rb:119:in `each'
	from node_modules/@pact-foundation/pact-node/standalone/darwin-1.47.2/lib/vendor/ruby/2.2.0/gems/pact-1.28.0/lib/pact/provider/pact_spec_runner.rb:119:in `initialize_specs'
	from node_modules/@pact-foundation/pact-node/standalone/darwin-1.47.2/lib/vendor/ruby/2.2.0/gems/pact-1.28.0/lib/pact/provider/pact_spec_runner.rb:34:in `run'
```

**Comment by mefellows** [comment]
Thanks @shavo007, can you please paste the output of `stdout` during the run. You should see something like:

```
[2018-07-13T00:05:28.594Z] DEBUG: pact-node@6.19.4/97417 on Matts-iMac.local: Finding consumers
[2018-07-13T00:05:28.594Z] DEBUG: pact-node@6.19.4/97417 on Matts-iMac.local: finding pacts for Provider: Animal Profile Service Tag: undefined
[2018-07-13T00:05:32.916Z] DEBUG: pact-node@6.19.4/97417 on Matts-iMac.local: Starting pact binary with '/bin/sh,[object Object],{"cwd":"/Users/mfellows/development/public/pact-js/node_modules/@pact-foundation/pact-node","detached":true,"env":{"npm_config_save_dev":"","npm_config_legacy_bundling":"","npm_config_dry_run":"","CLOUDFLARE_API_KEY":"6a23f6371f12d818cb3368c996f5e84562eff",
...
```

This will help us see what pact-node is trying to do.

**Comment by shavo007** [comment]
BTW, i am using node 10.5.0

there is alot of output here but it starts with 

```
[2018-07-13T01:11:20.700Z]  INFO: pact-node@6.19.4/363 on L3010: Verifying Pacts.
[2018-07-13T01:11:20.704Z]  INFO: pact-node@6.19.4/363 on L3010: Verifying Pact Files
[2018-07-13T01:11:20.707Z] DEBUG: pact-node@6.19.4/363 on L3010: Starting pact binary with '/bin/sh,[object Object],{"cwd":"node_modules/@pact-foundation/pact-node","detached":true,"env":{"npm_package_devDependencies_lint_staged":"7.2.0","npm_package_nyc_lines":"78","npm_package_devDependencies_prettier":"1.13.7","npm_package_nyc_functions":"80","npm_package_nyc_instrument":"false","npm_package_nyc_exclude_4":"src/**/apiConstants.js","TERM_PROGRAM":"iTerm.app","npm_package_nyc_exclude_3":"src/config","npm_package_devDependencies__pact_foundation_pact":"5.9.1","LESS_TERMCAP_md":"\u001b[38;5;136m","NODE":"/Users/slee/.nvm/versions/node/v10.5.0/bin/node",

```

```
[2018-07-13T01:11:20.712Z]  INFO: pact-node@6.19.4/363 on L3010: Created './standalone/darwin-1.47.2/bin/pact-provider-verifier 'http://localhost' --provider-base-url 'http://api.blah' --broker-username 'shanelee007' --broker-password 'xxx' --publish-verification-results 'true' --provider-app-version '2.0.0'' process with PID: 364
[2018-07-13T01:11:21.669Z] DEBUG: pact-node@6.19.4/363 on L3010:
   node_modules/@pact-foundation/pact-node/standalone/darwin-1.47.2/lib/vendor/ruby/2.2.0/gems/pact-support-1.6.2/lib/pact/consumer_contract/consumer_contract.rb:44:in `from_hash': No consumer contract parser found for hash: {"_links"=>{"self"=>{"href"=>"http://localhost", "title"=>"Index", "templated"=>false}, "pb:publish-pact"=>{"href"=>"http://localhost/pacts/provider/{provider}/consumer/{consumer}/version/{consumerApplicationVersion}", "title"=>"Publish a pact", "templated"=>true}, "pb:latest-pact-versions"=>{"href"=>"http://localhost/pacts/latest", "title"=>"Latest pact versions", "templated"=>false}, "pb:pacticipants"=>{"href"=>"http://localhost/pacticipants", "title"=>"Pacticipants", "templated"=>false}, "pb:latest-provider-pacts"=>{"href"=>"http://localhost/pacts/provider/{provider}/latest", "title"=>"Latest pacts by provider", "templated"=>true}, "pb:latest-provider-pacts-with-tag"=>{"href"=>"http://localhost/pacts/provider/{provider}/latest/{tag}", "title"=>"Latest pacts for provider with the specified tag", "templated"=>true}, "pb:provider-pacts-with-tag"=>{"href"=>"http://localhost/pacts/provider/{provider}/tag/{tag}", "title"=>"All pact versions for the provider with the specified consumer version tag", "templated"=>true}, "pb:provider-pacts"=>{"href"=>"http://localhost/pacts/provider/{provider}", "title"=>"All pact versions for the specified provider", "templated"=>true}, "pb:latest-version"=>{"href"=>"http://localhost/pacticipants/{pacticipant}/latest-version", "title"=>"Latest pacticipant version", "templated"=>true}, "pb:latest-tagged-version"=>{"href"=>"http://localhost/pacticipants/{pacticipant}/latest-version/{tag}", "title"=>"Latest pacticipant version with the specified tag", "templated"=>true}, "pb:webhooks"=>{"href"=>"http://localhost/webhooks", "title"=>"Webhooks", "templated"=>false}, "curies"=>[{"name"=>"pb", "href"=>"http://localhost/doc/{rel}?context=index", "templated"=>true}]}} (Pact::Error)
    	
```

**Comment by mefellows** [comment]
AH, I see it.

```
pactUrls: ['http://localhost'], // the pacts to test against
```

This is a list of _known_ pact URLs. If you want to fetch from the broker, you need to specify the pact broker URL, e.g.

```
pactBrokerUrl: 'http://localhost',
```

This is why we're not seeing `"Finding consumers ..."` at the start.

**Comment by shavo007** [comment]
voila, that worked @mefellows!!!

```
pactBrokerUrl: 'http://localhost', // the pacts to test against
```

i think the docs are a bit confusing.

why have two fields for pact broker url? 

https://github.com/pact-foundation/pact-node#provider-verification

**Comment by shavo007** [comment]
pactBrokerUrl which is a string and pactUrls which is an array

**Comment by shavo007** [comment]
also `providerVersion ` is a boolean, i believe it should be a string?

**Comment by mefellows** [comment]
Yep, I can see how it's a bit confusing, I'll update the docs shortly.

We don't actually have two fields for a pact broker url - `pactUrl` just takes an arbitrary number of URIs where pacts reside - whether local files or on remote HTTP systems (it just so happens that you _can_ point broker URLs in their to the specific pact files). 

`pactBrokerUrl` tells the verifier to use the broker discovery system to find all relevant pacts. 

Does that make sense?

**Comment by shavo007** [comment]
yes and no @mefellows !

i was under the assumption pacts are verified by a broker?
but i guess you could host them on a http server if you wanted.

i guess its an easy mistake but the error i got would not help me decipher what was wrong!

thanks for your help anyway

**Comment by mefellows** [comment]
It didn't help me either - so I agree with you there.

I'll raise an issue over in the verifier repo to see what we can do.

**Comment by shavo007** [comment]
👍

**Comment by bethesque** [comment]
> i was under the assumption pacts are verified by a broker?

Pact generation and verification happens on your machine. The pact broker stores the pacts and verification results.
